 export const Sentiment = [
    {
      id: 1,
      polarity:'مثبت',
      percentSentiment: 63,
      text:' عالی بود',
      year: 1391,
      month:1,
      day:22,
      nameOfLanguage:'پرتغالی',
      percentLanguage: 86,
      titleOfSource:'نظرات تیک تاک',
      percentSource:40,
      titleOfAspect:'وزن',
    },
    {
      id: 2,
      polarity:'مثبت',
      percentSentiment: 24,
      text:' بد بود',
      year: 1391,
      month:1,
      day:22,
      nameOfLanguage:'کره ای',
      percentLanguage: 58,
      titleOfSource:'گوگل',
      percentSource: 12,
      titleOfAspect:' حافظه‌ی رم',
    },
    {
      id: 3,
      polarity:'منفی',
      percentSentiment:91,
      text:'ویدئو قشنگی بود',
      year: 1391,
      month:1,
      day:22,
      nameOfLanguage:'هلندی ',
      percentLanguage:75,
      titleOfSource:'توییتر',
      percentSource: 17,      
      titleOfAspect:' سرعت پردازش',
    },
    {
        id: 4,
        polarity:'منفی',
        percentSentiment: 50,
        text:' عالی بود',
        year: 1391,
        month:1,
        day:22,
        nameOfLanguage:'هلندی ',
        percentLanguage:45,
        titleOfSource:'بارگذاری',
        percentSource: 15,
        titleOfAspect:'صفحه نمایش',
        titleOfAspect2:' عمر باتری ',
        titleOfAspect3:'وزن',
        },
        {
          id: 5,
          polarity:'مثبت',
          percentSentiment: 99,
          text:' بد بود',
          year: 1391,
          month:4,
          day:2,
          percentLanguage: 91,
          nameOfLanguage:'آلمانی',
          titleOfSource:'ویدئو تیک تاک',
          percentSource: 70,
          titleOfAspect:' سرعت پردازش',
      },
      {
        id:6,
        polarity:'منفی',
        percentSentiment: 52,
        text:' عالی بود',
        year: 1392,
        month:2,
        day:18,
        nameOfLanguage:'پرتغالی',
        percentLanguage: 62,
        titleOfSource:'گوگل',
        percentSource: 44,
        titleOfAspect:'وزن',
      },
      {
        id:7,
        polarity:'خنثی',
        percentSentiment:31,
        text:'ویدئو قشنگی بود',
         year: 1392,
         month:6,
         day:12,
         nameOfLanguage:'آلمانی',
         percentLanguage: 109,
         titleOfSource:'توییتر',
         percentSource: 108,
         titleOfAspect:'صفحه نمایش',
      },
      {
        id:8,
        polarity:'مثبت',
        percentSentiment: 49,
        text:' عالی بود',
        year: 1392,
        month:5,
        day:5,
        nameOfLanguage:'کره ای',
        percentLanguage: 83,
        titleOfSource:'بارگذاری',
        percentSource: 14,
        titleOfAspect:' حافظه‌ی رم',
        titleOfAspect2:'ابعاد',
      },
      {
        id:9,
        polarity:'خنثی',
        percentSentiment: 19,
        text:' بد بود',
        year: 1393,
        month:7,
        day:6,
        nameOfLanguage:'پرتغالی',
        percentLanguage: 16,
        titleOfSource:'ویدئو تیک تاک',
        percentSource: 33,
        titleOfAspect:'صفحه نمایش',
      },
      {
        id:10,
        polarity:'خنثی',
        percentSentiment:31,
        text:'ویدئو قشنگی بود',
        year: 1393,
        month:1,
        day:22,
        nameOfLanguage:'آلمانی',
        percentLanguage: 20,
        titleOfSource:'گوگل',
        percentSource: 70,
        titleOfAspect:'ابعاد',
      },
      {
        id:11,
        polarity:'خنثی',
        percentSentiment:39,
        text:'ویدئو قشنگی بود',
        year: 1393,
        month:11,
        day:11,
        nameOfLanguage:'تایلندی ',
        percentLanguage: 88,
        titleOfSource:'اینستاگرام',
        percentSource:22,
          titleOfAspect:' عمر باتری ',
          titleOfAspect2:' دوربین',
      },
      {
         id: 12,
          polarity:'مثبت',
          percentSentiment: 19,
          text:' عالی بود',
          year: 1396,
          month:11,
          day:22,
          nameOfLanguage:'کره ای',
          percentLanguage: 73,
          titleOfSource:'توییتر',
          percentSource: 20,
         titleOfAspect:'ابعاد',
        },
        {
          id: 13,
          polarity:'خنثی',
          percentSentiment:31,
          text:'ویدئو قشنگی بود',
          year: 1396,
          month:7,
          day:16,
          nameOfLanguage:'انگلیسی',
          percentLanguage: 50,
          titleOfSource:'گوگل',
          percentSource: 70,
          titleOfAspect:' عمر باتری ',
        },
        {
          id: 14,
          polarity:'مثبت',
          percentSentiment: 36,
          text:' عالی بود',
          year: 1396,
          month:11,
          day:11,
          nameOfLanguage:'پرتغالی',
          percentLanguage: 98,
          titleOfSource:'بارگذاری',
          percentSource: 42,
          titleOfAspect:' برند',
        },
        {
          id: 15,
          polarity:'خنثی',
         percentSentiment: 69,
         text:' بد بود',
          year: 1396,
          month:1,
          day:7,
          nameOfLanguage:'اندونزی',
          percentLanguage: 50,
          titleOfSource:'گوگل',
          percentSource: 47,
          titleOfAspect:' عمر باتری ',
        },
        {
          id: 16,
          polarity:'مثبت',
          percentSentiment: 59,
          text:' عالی بود',
          year: 1393,
          month:5,
          day:6,
          nameOfLanguage:'انگلیسی',
          percentLanguage: 66,
          titleOfSource:'اینستاگرام',
          percentSource: 14,
          titleOfAspect:' دوربین',
        },
        {
          id: 17,
          polarity:'خنثی',
          percentSentiment: 50,
          text:' عالی بود',
          year: 1398,
          month:11,
          day:14,
          nameOfLanguage:'تایلندی ',
          percentLanguage: 13,
          titleOfSource:'بارگذاری',
          percentSource: 11,
         titleOfAspect:' سرعت پردازش',
         titleOfAspect2:' برند',
        },
        {
          id: 18,
          polarity:'منفی',
          percentSentiment:31,
          text:'ویدئو قشنگی بود',
          year: 1398,
          month:12,
          day:24,
          nameOfLanguage:'انگلیسی',
          percentLanguage: 10,
          titleOfSource:'نظرات تیک تاک',
          percentSource: 70,     
          titleOfAspect:' برند',
        },
        {
          id: 19,
         polarity:'منفی',
         percentSentiment: 89,
         text:' بد بود',
          year: 1398,
          month:3,
          day:23,
          nameOfLanguage:'اندونزی',
          percentLanguage: 10,
         titleOfSource:'اینستاگرام',
         percentSource: 7,
          titleOfAspect:' دوربین',
          titleOfAspect2:' برند',
          titleOfAspect3:' سرعت پردازش',
        },
        {
          id: 20,
          polarity:'مثبت',
          percentSentiment: 88,
          text:' عالی بود',
          year: 1398,
          month:5,
          day:4,
          nameOfLanguage:'اسپانیایی',
          percentLanguage: 105,
          titleOfSource:'گوگل',
          percentSource: 27,
          titleOfAspect:' برند',
        },
        {
          id: 21,
          polarity:'مثبت',
          percentSentiment: 63,
          text:' عالی بود',
          year: 1396,
          month:1,
          day:22,
          nameOfLanguage:'پرتغالی',
          percentLanguage: 86,
          titleOfSource:'نظرات تیک تاک',
          percentSource:40,
          titleOfAspect:'وزن',
        },
        {
          id: 22,
          polarity:'منفی',
          percentSentiment: 24,
          text:' بد بود',
          year: 1398,
          month:1,
          day:22,
          nameOfLanguage:'کره ای',
          percentLanguage: 58,
          titleOfSource:'گوگل',
          percentSource: 12,
          titleOfAspect:' حافظه‌ی رم',
        },
        {
          id: 23,
          polarity:'خنثی',
          percentSentiment:91,
          text:'ویدئو قشنگی بود',
          year: 1391,
          month:1,
          day:22,
          nameOfLanguage:'هلندی ',
          percentLanguage:75,
          titleOfSource:'نظرات تیک تاک',
          percentSource: 17,      
          titleOfAspect:' سرعت پردازش',
        },
        {
            id: 24,
            polarity:'مثبت',
            percentSentiment: 50,
            text:' عالی بود',
            year: 1392,
            month:1,
            day:22,
            nameOfLanguage:'هلندی ',
            percentLanguage:45,
            titleOfSource:'بارگذاری',
            percentSource: 15,
            titleOfAspect:'صفحه نمایش',
            titleOfAspect2:' عمر باتری ',
            titleOfAspect3:'وزن',
            },
            {
              id: 25,
              polarity:'منفی',
              percentSentiment: 19,
              text:' بد بود',
              year: 1393,
              month:4,
              day:2,
              percentLanguage: 91,
              nameOfLanguage:'آلمانی',
              titleOfSource:'ویدئو تیک تاک',
              percentSource: 7,
              titleOfAspect:' سرعت پردازش',
          },
  ];