 export const Sentiment = [
    {
      id: 1,
      polarity:'مثبت',
      text:' سبک  است',
      year: 1391,
      month:1,
      day:22,
      nameOfLanguage:'انگلیسی',
      titleOfSource:'گوگل',
      titleOfAspect1:'وزن',
    },
    {
      id: 2,
      polarity:'مثبت',
      text:' حافظه کافی دارد و سنگین نیست',
      year: 1391,
      month:1,
      day:22,
      nameOfLanguage:'تایلندی',
      titleOfSource:'اینستاگرام',
      titleOfAspect1:' حافظه‌ی رم',
      titleOfAspect2:'وزن',
    },
    {
      id: 3,
      polarity:'منفی',
      text:'سرعت پایینی دارد',
      year: 1391,
      month:1,
      day:22,
      nameOfLanguage:'هلندی',
      titleOfSource:'گوگل',
      titleOfAspect1:' سرعت پردازش',
    },
    {
        id: 4,
        polarity:'منفی',
        text:' بد بود',
        year: 1391,
        month:1,
        day:22,
        nameOfLanguage:'اسپانیایی',
        titleOfSource:'اینستاگرام',
        titleOfAspect1:'صفحه نمایش',
        titleOfAspect2:' عمر باتری ',
        titleOfAspect3:'وزن',
        },
        {
          id: 5,
          polarity:'خنثی',
          text:' بد بود',
          year: 1391,
          month:4,
          day:2,
          nameOfLanguage:'آلمانی',
          titleOfSource:'گوگل',
          titleOfAspect1:' سرعت پردازش',
      },
      {
        id:6,
        polarity:'منفی',
        text:' بد بود',
        year: 1391,
        month:2,
        day:18,
        nameOfLanguage:'پرتغالی',
        titleOfSource:'بارگذاری',
        titleOfAspect1:'وزن',
      },
      {
        id:7,
        polarity:'خنثی',
        text:'  خوب است',
         year: 1391,
         month:6,
         day:12,
         nameOfLanguage:'آلمانی',
         titleOfSource:'اینستاگرام',
         titleOfAspect1:'صفحه نمایش',
      },
      {
        id:8,
        polarity:'مثبت',
        text:' عالی بود',
        year: 1391,
        month:5,
        day:5,
        nameOfLanguage:'اندونزی',
        titleOfSource:'بارگذاری',
        titleOfAspect1:' حافظه‌ی رم',
        titleOfAspect2:'ابعاد',
      },
      {
        id:9,
        polarity:'منفی',
        text:' بد بود',
        year: 1391,
        month:7,
        day:6,
        nameOfLanguage:'پرتغالی',
        titleOfSource:'توییتر',
        titleOfAspect1:'صفحه نمایش',
      },
      {
        id:10,
        polarity:'منفی',
        text:' بد بود',
        year: 1391,
        month:7,
        day:6,
        nameOfLanguage:'پرتغالی',
        titleOfSource:'نظرات تیک تاک',
        titleOfAspect1:'صفحه نمایش',
      },
      {
        id:11,
        polarity:'مثبت',
        text:' جالب بود',
        year: 1391,
        month:1,
        day:22,
        nameOfLanguage:'آلمانی',
        titleOfSource:'اینستاگرام',
        titleOfAspect1:'ابعاد',
      },
      {
        id:12,
        polarity:'خنثی',
        text:' جالب بود',
        year: 1391,
        month:11,
        day:11,
        nameOfLanguage:'تایلندی',
        titleOfSource:'بارگذاری',
          titleOfAspect1:' عمر باتری ',
          titleOfAspect2:' دوربین',
      },
      {
        id:13,
        polarity:'خنثی',
        text:' جالب بود',
        year: 1391,
        month:11,
        day:11,
        nameOfLanguage:'کره ای',
        titleOfSource:'ویدئو تیک تاک',
          titleOfAspect1:' عمر باتری ',
          titleOfAspect2:' دوربین',
      },
      {
        id: 14,
         polarity:'مثبت',
         text:' عالی بود',
         year: 1391,
         month:11,
         day:22,
         nameOfLanguage:'اسپانیایی',
         titleOfSource:'توییتر',
        titleOfAspect1:'ابعاد',
       },
       {
         id: 15,
         polarity:'خنثی',
         text:' جالب بود',
         year: 1391,
         month:7,
         day:16,
         nameOfLanguage:'انگلیسی',
         titleOfSource:'توییتر',
         titleOfAspect1:' عمر باتری ',
       },
      {
         id: 16,
          polarity:'مثبت',
          text:' عالی بود',
          year: 1392,
          month:11,
          day:22,
          nameOfLanguage:'اسپانیایی',
          titleOfSource:'توییتر',
         titleOfAspect1:'ابعاد',
        },
        {
          id: 17,
          polarity:'خنثی',
          text:' بد نبود',
          year: 1392,
          month:7,
          day:16,
          nameOfLanguage:'انگلیسی',
          titleOfSource:'توییتر',
          titleOfAspect1:' عمر باتری ',
        },
        {
          id: 18,
          polarity:'منفی',
          text:' بد بود',
          year: 1392,
          month:11,
          day:11,
          nameOfLanguage:'تایلندی',
          titleOfSource:'ویدئو تیک تاک',
          titleOfAspect1:' برند',
        },
        {
          id: 19,
          polarity:'خنثی',
         text:' بد بود',
          year: 1392,
          month:1,
          day:7,
          nameOfLanguage:'اندونزی',
          titleOfSource:'نظرات تیک تاک',
          titleOfAspect1:' عمر باتری ',
        },
        {
          id: 20,
          polarity:'منفی',
          text:' بد بود',
          year: 1392,
          month:5,
          day:6,
          nameOfLanguage:'انگلیسی',
          titleOfSource:'بارگذاری',
          titleOfAspect1:' برند',
        },
        {
          id: 21,
          polarity:'خنثی',
          text:' عالی بود',
          year: 1392,
          month:11,
          day:14,
          nameOfLanguage:'تایلندی',
          titleOfSource:'بارگذاری',
         titleOfAspect1:' سرعت پردازش',
         titleOfAspect2:' برند',
        },
        {
          id: 22,
          polarity:'منفی',
          text:' خوب نبود',
          year: 1392,
          month:12,
          day:24,
          nameOfLanguage:'آلمانی',
          titleOfSource:'توییتر',
          titleOfAspect1:' برند',
        },
        {
          id: 23,
         polarity:'منفی',
         text:' بد بود',
          year: 1392,
          month:3,
          day:23,
          nameOfLanguage:'اندونزی',
         titleOfSource:'اینستاگرام',
          titleOfAspect1:' برند',
          titleOfAspect2:' دوربین',
          titleOfAspect3:' سرعت پردازش',
        },
        {
          id: 24,
          polarity:'مثبت',
          text:' عالی بود',
          year: 1392,
          month:5,
          day:4,
          nameOfLanguage:'هلندی',
          titleOfSource:'گوگل',
          titleOfAspect1:' برند',
        },
        {
          id: 25,
          polarity:'مثبت',
          text:' عالی بود',
          year: 1392,
          month:1,
          day:22,
          nameOfLanguage:'کره ای',
          titleOfSource:'نظرات تیک تاک',
          titleOfAspect1:'وزن',
        },
        {
          id: 26,
          polarity:'منفی',
          text:' بد بود',
          year: 1392,
          month:1,
          day:22,
          nameOfLanguage:'کره ای',
          titleOfSource:'نظرات تیک تاک',
          titleOfAspect1:' حافظه‌ی رم',
        },
        {
          id: 27,
          polarity:'مثبت',
          text:' عالی بود',
          year: 1392,
          month:1,
          day:22,
          nameOfLanguage:'پرتغالی',
          titleOfSource:'بارگذاری',
          titleOfAspect1:'صفحه نمایش',
          titleOfAspect2:' عمر باتری ',
          titleOfAspect3:'وزن',
          },
        {
          id: 28,
          polarity:'خنثی',
          text:' جالب بود',
          year: 1393,
          month:1,
          day:22,
          nameOfLanguage:'هلندی',
          titleOfSource:'اینستاگرام',
          titleOfAspect1:' سرعت پردازش',
        },
        {
            id: 29,
            polarity:'مثبت',
            text:' عالی بود',
            year: 1393,
            month:1,
            day:22,
            nameOfLanguage:'پرتغالی',
            titleOfSource:'بارگذاری',
            titleOfAspect1:'صفحه نمایش',
            titleOfAspect2:' عمر باتری ',
            titleOfAspect3:'وزن',
            },
            {
              id: 30,
              polarity:'مثبت',
              text:' عالی بود',
              year: 1393,
              month:4,
              day:2,
              nameOfLanguage:'آلمانی',
              titleOfSource:'ویدئو تیک تاک',
              titleOfAspect1:' سرعت پردازش',
          },
          {
            id: 31,
            polarity:'مثبت',
            text:' عالی بود',
            year: 1393,
            month:1,
            day:22,
            nameOfLanguage:'تایلندی',
            titleOfSource:'نظرات تیک تاک',
            titleOfAspect1:'وزن',
          },
          {
            id: 32,
            polarity:'منفی',
            text:' بد بود',
            year: 1393,
            month:1,
            day:22,
            nameOfLanguage:'کره ای',
            titleOfSource:'گوگل',
            titleOfAspect1:' حافظه‌ی رم',
          },
          {
            id: 33,
            polarity:'خنثی',
            text:' جالب بود',
            year: 1393,
            month:1,
            day:22,
            nameOfLanguage:'هلندی',
            titleOfSource:'نظرات تیک تاک',
            titleOfAspect1:' سرعت پردازش',
          },
          {
              id: 34,
              polarity:'مثبت',
              text:' عالی بود',
              year: 1393,
              month:1,
              day:22,
              nameOfLanguage:'هلندی',
              titleOfSource:'بارگذاری',
              titleOfAspect1:'صفحه نمایش',
              titleOfAspect2:' عمر باتری ',
              titleOfAspect3:'وزن',
              },
              {
                id: 35,
                polarity:'مثبت',
                text:' عالی بود',
                year: 1393,
                month:4,
                day:2,
                nameOfLanguage:'آلمانی',
                titleOfSource:'توییتر',
                titleOfAspect1:' سرعت پردازش',
            },
            {
              id: 36,
               polarity:'مثبت',
               text:' عالی بود',
               year: 1393,
               month:11,
               day:22,
               nameOfLanguage:'اسپانیایی',
               titleOfSource:'توییتر',
              titleOfAspect1:'ابعاد',
             },
             {
               id: 37,
               polarity:'خنثی',
               text:' جالب بود',
               year: 1393,
               month:7,
               day:16,
               nameOfLanguage:'انگلیسی',
               titleOfSource:'توییتر',
               titleOfAspect1:' عمر باتری ',
             },
             {
              id:38,
              polarity:'مثبت',
              text:' عالی بود',
              year: 1393,
              month:5,
              day:5,
              nameOfLanguage:'اندونزی',
              titleOfSource:'بارگذاری',
              titleOfAspect1:' حافظه‌ی رم',
              titleOfAspect2:'ابعاد',
            },
            {
            id: 39,
            polarity:'مثبت',
            text:' سبک  است',
            year: 1396,
            month:1,
            day:22,
            nameOfLanguage:'پرتغالی',
            titleOfSource:'توییتر',
            titleOfAspect1:'وزن',
          },
          {
            id: 40,
            polarity:'خنثی',
            text:' حافظه کافی دارد و سنگین نیست',
            year: 1396,
            month:1,
            day:22,
            nameOfLanguage:'کره ای',
            titleOfSource:'گوگل',
            titleOfAspect1:' حافظه‌ی رم',
            titleOfAspect2:'وزن',
          },
          {
            id: 41,
            polarity:'منفی',
            text:'سرعت پایینی دارد',
            year: 1396,
            month:1,
            day:22,
            nameOfLanguage:'هلندی',
            titleOfSource:'توییتر',
            titleOfAspect1:' سرعت پردازش',
          },
          {
              id: 42,
              polarity:'منفی',
              text:' بد بود',
              year: 1396,
              month:1,
              day:22,
              nameOfLanguage:'اسپانیایی',
              titleOfSource:'بارگذاری',
              titleOfAspect1:'صفحه نمایش',
              titleOfAspect2:' عمر باتری ',
              titleOfAspect3:'وزن',
              },
              {
                id: 43,
                polarity:'خنثی',
                text:' بد نبود',
                year: 1396,
                month:4,
                day:2,
                nameOfLanguage:'اسپانیایی',
                titleOfSource:'نظرات تیک تاک',
                titleOfAspect1:' سرعت پردازش',
            },
            {
              id:44,
              polarity:'منفی',
              text:' بد بود',
              year: 1396,
              month:2,
              day:18,
              nameOfLanguage:'پرتغالی',
              titleOfSource:'گوگل',
              titleOfAspect1:'وزن',
            },
            {
              id:45,
              polarity:'خنثی',
              text:' جالب بود',
               year: 1396,
               month:6,
               day:12,
               nameOfLanguage:'آلمانی',
               titleOfSource:'اینستاگرام',
               titleOfAspect1:'صفحه نمایش',
            },
            {
              id:46,
              polarity:'مثبت',
              text:' عالی بود',
              year: 1396,
              month:5,
              day:5,
              nameOfLanguage:'کره ای',
              titleOfSource:'بارگذاری',
              titleOfAspect1:' حافظه‌ی رم',
              titleOfAspect2:'ابعاد',
            },
            {
              id:47,
              polarity:'خنثی',
              text:' بد نبود',
              year: 1396,
              month:7,
              day:6,
              nameOfLanguage:'پرتغالی',
              titleOfSource:'ویدئو تیک تاک',
              titleOfAspect1:'صفحه نمایش',
            },
            {
              id:48,
              polarity:'منفی',
              text:' جالب نبود',
              year: 1396,
              month:1,
              day:22,
              nameOfLanguage:'آلمانی',
              titleOfSource:'گوگل',
              titleOfAspect1:'ابعاد',
            },
            {
              id: 49,
               polarity:'مثبت',
               text:' عالی بود',
               year: 1396,
               month:11,
               day:22,
               nameOfLanguage:'اسپانیایی',
               titleOfSource:'توییتر',
              titleOfAspect1:'ابعاد',
             },
             {
               id: 50,
               polarity:'خنثی',
               text:' جالب بود',
               year: 1396,
               month:7,
               day:16,
               nameOfLanguage:'انگلیسی',
               titleOfSource:'توییتر',
               titleOfAspect1:' عمر باتری ',
             },
             {
              id:51,
              polarity:'خنثی',
              text:' بد نبود',
              year: 1396,
              month:7,
              day:6,
              nameOfLanguage:'تایلندی',
              titleOfSource:'ویدئو تیک تاک',
              titleOfAspect1:'صفحه نمایش',
            },
            {
              id:52,
              polarity:'مثبت',
              text:' عالی بود',
              year: 1396,
              month:5,
              day:5,
              nameOfLanguage:'اندونزی',
              titleOfSource:'بارگذاری',
              titleOfAspect1:' حافظه‌ی رم',
              titleOfAspect2:'ابعاد',
            },
            {
              id: 53,
              polarity:'مثبت',
              text:' عالی بود',
              year: 1398,
              month:1,
              day:22,
              nameOfLanguage:'هلندی',
              titleOfSource:'بارگذاری',
              titleOfAspect1:'صفحه نمایش',
              titleOfAspect2:' عمر باتری ',
              titleOfAspect3:'وزن',
              },
              {
                id: 54,
                polarity:'مثبت',
                text:' بد بود',
                year: 1398,
                month:4,
                day:2,
                nameOfLanguage:'آلمانی',
                titleOfSource:'ویدئو تیک تاک',
                titleOfAspect1:' سرعت پردازش',
            },
            {
            id: 55,
            polarity:'مثبت',
            text:' سبک  است',
            year: 1398,
            month:1,
            day:22,
            nameOfLanguage:'پرتغالی',
            titleOfSource:'نظرات تیک تاک',
            titleOfAspect1:'وزن',
          },
          {
            id: 56,
            polarity:'خنثی',
            text:' حافظه کافی دارد و سنگین نیست',
            year: 1398,
            month:1,
            day:22,
            nameOfLanguage:'کره ای',
            titleOfSource:'اینستاگرام',
            titleOfAspect1:' حافظه‌ی رم',
            titleOfAspect2:'وزن',
          },
          {
            id: 57,
            polarity:'منفی',
            text:'سرعت پایینی دارد',
            year: 1398,
            month:1,
            day:48,
            nameOfLanguage:'هلندی',
            titleOfSource:'توییتر',
            titleOfAspect1:' سرعت پردازش',
          },
          {
              id: 58,
              polarity:'منفی',
              text:' بد بود',
              year: 1398,
              month:1,
              day:22,
              nameOfLanguage:'اسپانیایی',
              titleOfSource:'بارگذاری',
              titleOfAspect1:'صفحه نمایش',
              titleOfAspect2:' عمر باتری ',
              titleOfAspect3:'وزن',
              },
              {
                id: 59,
                polarity:'خنثی',
                text:' بد نبود',
                year: 1398,
                month:4,
                day:2,
                nameOfLanguage:'اسپانیایی',
                titleOfSource:'توییتر',
                titleOfAspect1:' سرعت پردازش',
            },
            {
              id:60,
              polarity:'منفی',
              text:' بد بود',
              year: 1398,
              month:2,
              day:18,
              nameOfLanguage:'پرتغالی',
              titleOfSource:'گوگل',
              titleOfAspect1:'وزن',
            },
            {
              id:61,
              polarity:'خنثی',
              text:' خوب بود',
               year: 1398,
               month:6,
               day:12,
               nameOfLanguage:'آلمانی',
               titleOfSource:'توییتر',
               titleOfAspect1:'صفحه نمایش',
            },
            {
              id:62,
              polarity:'مثبت',
              text:' عالی بود',
              year: 1398,
              month:5,
              day:5,
              nameOfLanguage:'کره ای',
              titleOfSource:'بارگذاری',
              titleOfAspect1:' حافظه‌ی رم',
              titleOfAspect2:'ابعاد',
            },
            {
              id:63,
              polarity:'خنثی',
              text:' بد نبود',
              year: 1398,
              month:7,
              day:6,
              nameOfLanguage:'تایلندی',
              titleOfSource:'ویدئو تیک تاک',
              titleOfAspect1:'صفحه نمایش',
            },
            {
              id:64,
              polarity:'منفی',
              text:' خوب نبود',
              year: 1398,
              month:1,
              day:22,
              nameOfLanguage:'انگلیسی',
              titleOfSource:'گوگل',
              titleOfAspect1:'ابعاد',
            },
            {
              id:65,
              polarity:'مثبت',
              text:' عالی بود',
              year: 1396,
              month:5,
              day:5,
              nameOfLanguage:'اندونزی',
              titleOfSource:'بارگذاری',
              titleOfAspect1:' حافظه‌ی رم',
              titleOfAspect2:'ابعاد',
            },
            {
              id:66,
              polarity:'منفی',
              text:' بد بود',
              year: 1398,
              month:5,
              day:5,
              nameOfLanguage:'اندونزی',
              titleOfSource:'بارگذاری',
              titleOfAspect1:' حافظه‌ی رم',
              titleOfAspect2:'ابعاد',
            },
  ];