export const Sentiment = [
  {
    id: 1,
    polarity:'منفی',
    text:' سبک  است',
    year: 1391,
    month:1,
    day:22,
    nameOfLanguage:'انگلیسی',
    titleOfSource:'گوگل',
    titleOfAspect1:'وزن',
  },
  {
    id: 2,
    polarity:'منفی',
    text:' حافظه کافی دارد و سنگین نیست',
    year: 1398,
    month:1,
    day:22,
    nameOfLanguage:'تایلندی',
    titleOfSource:'اینستاگرام',
    titleOfAspect1:' حافظه‌ی رم',
    titleOfAspect2:'وزن',
  },
  {
    id: 3,
    polarity:'مثبت',
    text:'سرعت پایینی دارد',
    year: 1391,
    month:1,
    day:22,
    nameOfLanguage:'هلندی',
    titleOfSource:'گوگل',
    titleOfAspect1:'  سیستم آکوستیک',
  },
  {
      id: 4,
      polarity:'مثبت',
      text:' بد بود',
      year: 1391,
      month:1,
      day:22,
      nameOfLanguage:'اسپانیایی',
      titleOfSource:'اینستاگرام',
      titleOfAspect1:'محدوده پاسخ فرکانسی',
      titleOfAspect2:' قابلیت حذف نویز ',
      titleOfAspect3:'وزن',
      },
      {
        id: 5,
        polarity:'خنثی',
        text:' بد بود',
        year: 1391,
        month:4,
        day:2,
        nameOfLanguage:'آلمانی',
        titleOfSource:'گوگل',
        titleOfAspect1:'  سیستم آکوستیک',
    },
    {
      id:6,
      polarity:'مثبت',
      text:' بد بود',
      year: 1391,
      month:2,
      day:18,
      nameOfLanguage:'پرتغالی',
      titleOfSource:'بارگذاری',
      titleOfAspect1:'وزن',
    },
    {
      id:7,
      polarity:'خنثی',
      text:'  خوب است',
       year: 1391,
       month:6,
       day:12,
       nameOfLanguage:'آلمانی',
       titleOfSource:'اینستاگرام',
       titleOfAspect1:'محدوده پاسخ فرکانسی',
    },
    {
      id:8,
      polarity:'منفی',
      text:' عالی بود',
      year: 1391,
      month:5,
      day:5,
      nameOfLanguage:'اندونزی',
      titleOfSource:'بارگذاری',
      titleOfAspect1:' حافظه‌ی رم',
      titleOfAspect2:'دیافراگم',
    },
    {
      id:9,
      polarity:'مثبت',
      text:' بد بود',
      year: 1391,
      month:7,
      day:6,
      nameOfLanguage:'پرتغالی',
      titleOfSource:'توییتر',
      titleOfAspect1:'محدوده پاسخ فرکانسی',
    },
    {
      id:10,
      polarity:'مثبت',
      text:' بد بود',
      year: 1391,
      month:7,
      day:6,
      nameOfLanguage:'پرتغالی',
      titleOfSource:'نظرات تیک تاک',
      titleOfAspect1:'محدوده پاسخ فرکانسی',
    },
    {
      id:11,
      polarity:'منفی',
      text:' جالب بود',
      year: 1391,
      month:1,
      day:22,
      nameOfLanguage:'آلمانی',
      titleOfSource:'اینستاگرام',
      titleOfAspect1:'دیافراگم',
    },
    {
      id:12,
      polarity:'خنثی',
      text:' جالب بود',
      year: 1391,
      month:11,
      day:11,
      nameOfLanguage:'تایلندی',
      titleOfSource:'بارگذاری',
        titleOfAspect1:' قابلیت حذف نویز ',
        titleOfAspect2:' دوربین',
    },
    {
      id:13,
      polarity:'خنثی',
      text:' جالب بود',
      year: 1391,
      month:11,
      day:11,
      nameOfLanguage:'کره ای',
      titleOfSource:'ویدئو تیک تاک',
        titleOfAspect1:' قابلیت حذف نویز ',
        titleOfAspect2:' دوربین',
    },
    {
      id: 14,
       polarity:'منفی',
       text:' عالی بود',
       year: 1391,
       month:11,
       day:22,
       nameOfLanguage:'اسپانیایی',
       titleOfSource:'توییتر',
      titleOfAspect1:'دیافراگم',
     },
     {
       id: 15,
       polarity:'خنثی',
       text:' جالب بود',
       year: 1391,
       month:7,
       day:16,
       nameOfLanguage:'انگلیسی',
       titleOfSource:'توییتر',
       titleOfAspect1:' قابلیت حذف نویز ',
     },
    {
       id: 16,
        polarity:'منفی',
        text:' عالی بود',
        year: 1392,
        month:11,
        day:22,
        nameOfLanguage:'اسپانیایی',
        titleOfSource:'توییتر',
       titleOfAspect1:'دیافراگم',
      },
      {
        id: 17,
        polarity:'خنثی',
        text:' بد نبود',
        year: 1392,
        month:7,
        day:16,
        nameOfLanguage:'انگلیسی',
        titleOfSource:'توییتر',
        titleOfAspect1:' قابلیت حذف نویز ',
      },
      {
        id: 18,
        polarity:'مثبت',
        text:' بد بود',
        year: 1392,
        month:11,
        day:11,
        nameOfLanguage:'تایلندی',
        titleOfSource:'ویدئو تیک تاک',
        titleOfAspect1:' برند',
      },
      {
        id: 19,
        polarity:'خنثی',
       text:' بد بود',
        year: 1392,
        month:1,
        day:7,
        nameOfLanguage:'اندونزی',
        titleOfSource:'نظرات تیک تاک',
        titleOfAspect1:' قابلیت حذف نویز ',
      },
      {
        id: 20,
        polarity:'مثبت',
        text:' بد بود',
        year: 1392,
        month:5,
        day:6,
        nameOfLanguage:'انگلیسی',
        titleOfSource:'بارگذاری',
        titleOfAspect1:' برند',
      },
      {
        id: 21,
        polarity:'خنثی',
        text:' عالی بود',
        year: 1392,
        month:11,
        day:14,
        nameOfLanguage:'تایلندی',
        titleOfSource:'بارگذاری',
       titleOfAspect1:' نوع آهنربا',
       titleOfAspect2:' برند',
      },
      {
        id: 22,
        polarity:'مثبت',
        text:' خوب نبود',
        year: 1392,
        month:12,
        day:24,
        nameOfLanguage:'آلمانی',
        titleOfSource:'توییتر',
        titleOfAspect1:' برند',
      },
      {
        id: 23,
       polarity:'مثبت',
       text:' بد بود',
        year: 1392,
        month:3,
        day:23,
        nameOfLanguage:'اندونزی',
       titleOfSource:'اینستاگرام',
        titleOfAspect1:' برند',
        titleOfAspect2:' دوربین',
        titleOfAspect3:' نوع آهنربا',
      },
      {
        id: 24,
        polarity:'منفی',
        text:' عالی بود',
        year: 1392,
        month:5,
        day:4,
        nameOfLanguage:'هلندی',
        titleOfSource:'گوگل',
        titleOfAspect1:' برند',
      },
      {
        id: 25,
        polarity:'منفی',
        text:' عالی بود',
        year: 1392,
        month:1,
        day:22,
        nameOfLanguage:'کره ای',
        titleOfSource:'نظرات تیک تاک',
        titleOfAspect1:'وزن',
      },
      {
        id: 26,
        polarity:'مثبت',
        text:' بد بود',
        year: 1392,
        month:1,
        day:22,
        nameOfLanguage:'کره ای',
        titleOfSource:'نظرات تیک تاک',
        titleOfAspect1:' حافظه‌ی رم',
      },
      {
        id: 27,
        polarity:'منفی',
        text:' عالی بود',
        year: 1392,
        month:1,
        day:22,
        nameOfLanguage:'پرتغالی',
        titleOfSource:'بارگذاری',
        titleOfAspect1:'محدوده پاسخ فرکانسی',
        titleOfAspect2:' قابلیت حذف نویز ',
        titleOfAspect3:'وزن',
        },
      {
        id: 28,
        polarity:'خنثی',
        text:' جالب بود',
        year: 1393,
        month:1,
        day:22,
        nameOfLanguage:'هلندی',
        titleOfSource:'اینستاگرام',
        titleOfAspect1:' نوع آهنربا',
      },
      {
          id: 29,
          polarity:'منفی',
          text:' عالی بود',
          year: 1393,
          month:1,
          day:22,
          nameOfLanguage:'پرتغالی',
          titleOfSource:'بارگذاری',
          titleOfAspect1:'محدوده پاسخ فرکانسی',
          titleOfAspect2:' قابلیت حذف نویز ',
          titleOfAspect3:'وزن',
          },
          {
            id: 30,
            polarity:'منفی',
            text:' عالی بود',
            year: 1393,
            month:4,
            day:2,
            nameOfLanguage:'آلمانی',
            titleOfSource:'ویدئو تیک تاک',
            titleOfAspect1:' نوع آهنربا',
        },
        {
          id: 31,
          polarity:'منفی',
          text:' عالی بود',
          year: 1393,
          month:1,
          day:22,
          nameOfLanguage:'تایلندی',
          titleOfSource:'نظرات تیک تاک',
          titleOfAspect1:'وزن',
        },
        {
          id: 32,
          polarity:'مثبت',
          text:' بد بود',
          year: 1393,
          month:1,
          day:22,
          nameOfLanguage:'کره ای',
          titleOfSource:'گوگل',
          titleOfAspect1:' حافظه‌ی رم',
        },
        {
          id: 33,
          polarity:'خنثی',
          text:' جالب بود',
          year: 1393,
          month:1,
          day:22,
          nameOfLanguage:'هلندی',
          titleOfSource:'نظرات تیک تاک',
          titleOfAspect1:' نوع آهنربا',
        },
        {
            id: 34,
            polarity:'منفی',
            text:' عالی بود',
            year: 1393,
            month:1,
            day:22,
            nameOfLanguage:'هلندی',
            titleOfSource:'بارگذاری',
            titleOfAspect1:'محدوده پاسخ فرکانسی',
            titleOfAspect2:' قابلیت حذف نویز ',
            titleOfAspect3:'وزن',
            },
            {
              id: 35,
              polarity:'منفی',
              text:' عالی بود',
              year: 1393,
              month:4,
              day:2,
              nameOfLanguage:'آلمانی',
              titleOfSource:'توییتر',
              titleOfAspect1:' نوع آهنربا',
          },
          {
            id: 36,
             polarity:'منفی',
             text:' عالی بود',
             year: 1393,
             month:11,
             day:22,
             nameOfLanguage:'اسپانیایی',
             titleOfSource:'توییتر',
            titleOfAspect1:'دیافراگم',
           },
           {
             id: 37,
             polarity:'خنثی',
             text:' جالب بود',
             year: 1393,
             month:7,
             day:16,
             nameOfLanguage:'انگلیسی',
             titleOfSource:'توییتر',
             titleOfAspect1:' قابلیت حذف نویز ',
           },
           {
            id:38,
            polarity:'منفی',
            text:' عالی بود',
            year: 1393,
            month:5,
            day:5,
            nameOfLanguage:'اندونزی',
            titleOfSource:'بارگذاری',
            titleOfAspect1:' حافظه‌ی رم',
            titleOfAspect2:'دیافراگم',
          },
          {
          id: 39,
          polarity:'منفی',
          text:' سبک  است',
          year: 1396,
          month:1,
          day:22,
          nameOfLanguage:'پرتغالی',
          titleOfSource:'توییتر',
          titleOfAspect1:'وزن',
        },
        {
          id: 40,
          polarity:'خنثی',
          text:' حافظه کافی دارد و سنگین نیست',
          year: 1396,
          month:1,
          day:22,
          nameOfLanguage:'کره ای',
          titleOfSource:'گوگل',
          titleOfAspect1:' حافظه‌ی رم',
          titleOfAspect2:'وزن',
        },
        {
          id: 41,
          polarity:'مثبت',
          text:'سرعت پایینی دارد',
          year: 1396,
          month:1,
          day:22,
          nameOfLanguage:'هلندی',
          titleOfSource:'توییتر',
          titleOfAspect1:' نوع آهنربا',
        },
        {
            id: 42,
            polarity:'مثبت',
            text:' بد بود',
            year: 1396,
            month:1,
            day:22,
            nameOfLanguage:'اسپانیایی',
            titleOfSource:'بارگذاری',
            titleOfAspect1:'محدوده پاسخ فرکانسی',
            titleOfAspect2:' قابلیت حذف نویز ',
            titleOfAspect3:'وزن',
            },
            {
              id: 43,
              polarity:'خنثی',
              text:' بد نبود',
              year: 1396,
              month:4,
              day:2,
              nameOfLanguage:'اسپانیایی',
              titleOfSource:'نظرات تیک تاک',
              titleOfAspect1:' نوع آهنربا',
          },
          {
            id:44,
            polarity:'مثبت',
            text:' بد بود',
            year: 1396,
            month:2,
            day:18,
            nameOfLanguage:'پرتغالی',
            titleOfSource:'گوگل',
            titleOfAspect1:'وزن',
          },
          {
            id:45,
            polarity:'خنثی',
            text:' جالب بود',
             year: 1396,
             month:6,
             day:12,
             nameOfLanguage:'آلمانی',
             titleOfSource:'اینستاگرام',
             titleOfAspect1:'محدوده پاسخ فرکانسی',
          },
          {
            id:46,
            polarity:'منفی',
            text:' عالی بود',
            year: 1396,
            month:5,
            day:5,
            nameOfLanguage:'کره ای',
            titleOfSource:'بارگذاری',
            titleOfAspect1:' حافظه‌ی رم',
            titleOfAspect2:'دیافراگم',
          },
          {
            id:47,
            polarity:'خنثی',
            text:' بد نبود',
            year: 1396,
            month:7,
            day:6,
            nameOfLanguage:'پرتغالی',
            titleOfSource:'ویدئو تیک تاک',
            titleOfAspect1:'محدوده پاسخ فرکانسی',
          },
          {
            id:48,
            polarity:'مثبت',
            text:' جالب نبود',
            year: 1396,
            month:1,
            day:22,
            nameOfLanguage:'آلمانی',
            titleOfSource:'گوگل',
            titleOfAspect1:'دیافراگم',
          },
          {
            id: 49,
             polarity:'منفی',
             text:' عالی بود',
             year: 1396,
             month:11,
             day:22,
             nameOfLanguage:'اسپانیایی',
             titleOfSource:'توییتر',
            titleOfAspect1:'دیافراگم',
           },
           {
             id: 50,
             polarity:'خنثی',
             text:' جالب بود',
             year: 1396,
             month:7,
             day:16,
             nameOfLanguage:'انگلیسی',
             titleOfSource:'توییتر',
             titleOfAspect1:' قابلیت حذف نویز ',
           },
           {
            id:51,
            polarity:'خنثی',
            text:' بد نبود',
            year: 1396,
            month:7,
            day:6,
            nameOfLanguage:'تایلندی',
            titleOfSource:'ویدئو تیک تاک',
            titleOfAspect1:'محدوده پاسخ فرکانسی',
          },
          {
            id:52,
            polarity:'منفی',
            text:' عالی بود',
            year: 1396,
            month:5,
            day:5,
            nameOfLanguage:'اندونزی',
            titleOfSource:'بارگذاری',
            titleOfAspect1:' حافظه‌ی رم',
            titleOfAspect2:'دیافراگم',
          },
          {
            id: 53,
            polarity:'منفی',
            text:' عالی بود',
            year: 1398,
            month:1,
            day:22,
            nameOfLanguage:'هلندی',
            titleOfSource:'بارگذاری',
            titleOfAspect1:'محدوده پاسخ فرکانسی',
            titleOfAspect2:' قابلیت حذف نویز ',
            titleOfAspect3:'وزن',
            },
            {
              id: 54,
              polarity:'منفی',
              text:' بد بود',
              year: 1398,
              month:4,
              day:2,
              nameOfLanguage:'آلمانی',
              titleOfSource:'ویدئو تیک تاک',
              titleOfAspect1:' نوع آهنربا',
          },
          {
          id: 55,
          polarity:'منفی',
          text:' سبک  است',
          year: 1398,
          month:1,
          day:22,
          nameOfLanguage:'پرتغالی',
          titleOfSource:'نظرات تیک تاک',
          titleOfAspect1:'وزن',
        },
        {
          id: 56,
          polarity:'خنثی',
          text:' حافظه کافی دارد و سنگین نیست',
          year: 1398,
          month:1,
          day:22,
          nameOfLanguage:'کره ای',
          titleOfSource:'اینستاگرام',
          titleOfAspect1:' حافظه‌ی رم',
          titleOfAspect2:'وزن',
        },
        {
          id: 57,
          polarity:'مثبت',
          text:'سرعت پایینی دارد',
          year: 1398,
          month:1,
          day:48,
          nameOfLanguage:'هلندی',
          titleOfSource:'توییتر',
          titleOfAspect1:' نوع آهنربا',
        },
        {
            id: 58,
            polarity:'مثبت',
            text:' بد بود',
            year: 1398,
            month:1,
            day:22,
            nameOfLanguage:'اسپانیایی',
            titleOfSource:'بارگذاری',
            titleOfAspect1:'محدوده پاسخ فرکانسی',
            titleOfAspect2:' قابلیت حذف نویز ',
            titleOfAspect3:'وزن',
            },
            {
              id: 59,
              polarity:'خنثی',
              text:' بد نبود',
              year: 1398,
              month:4,
              day:2,
              nameOfLanguage:'اسپانیایی',
              titleOfSource:'توییتر',
              titleOfAspect1:' نوع آهنربا',
          },
          {
            id:60,
            polarity:'مثبت',
            text:' بد بود',
            year: 1398,
            month:2,
            day:18,
            nameOfLanguage:'پرتغالی',
            titleOfSource:'گوگل',
            titleOfAspect1:'وزن',
          },
          {
            id:61,
            polarity:'خنثی',
            text:' خوب بود',
             year: 1398,
             month:6,
             day:12,
             nameOfLanguage:'آلمانی',
             titleOfSource:'توییتر',
             titleOfAspect1:'محدوده پاسخ فرکانسی',
          },
          {
            id:62,
            polarity:'منفی',
            text:' عالی بود',
            year: 1398,
            month:5,
            day:5,
            nameOfLanguage:'کره ای',
            titleOfSource:'بارگذاری',
            titleOfAspect1:' حافظه‌ی رم',
            titleOfAspect2:'دیافراگم',
          },
          {
            id:63,
            polarity:'خنثی',
            text:' بد نبود',
            year: 1398,
            month:7,
            day:6,
            nameOfLanguage:'تایلندی',
            titleOfSource:'ویدئو تیک تاک',
            titleOfAspect1:'محدوده پاسخ فرکانسی',
          },
          {
            id:64,
            polarity:'مثبت',
            text:' خوب نبود',
            year: 1398,
            month:1,
            day:22,
            nameOfLanguage:'انگلیسی',
            titleOfSource:'گوگل',
            titleOfAspect1:'دیافراگم',
          },
          {
            id:65,
            polarity:'منفی',
            text:' عالی بود',
            year: 1396,
            month:5,
            day:5,
            nameOfLanguage:'اندونزی',
            titleOfSource:'بارگذاری',
            titleOfAspect1:' حافظه‌ی رم',
            titleOfAspect2:'دیافراگم',
          },
          {
            id:66,
            polarity:'مثبت',
            text:' بد بود',
            year: 1398,
            month:5,
            day:5,
            nameOfLanguage:'اندونزی',
            titleOfSource:'بارگذاری',
            titleOfAspect1:' حافظه‌ی رم',
            titleOfAspect2:'دیافراگم',
          },        {
            id: 67,
            polarity:'منفی',
            text:' عالی بود',
            year: 1393,
            month:1,
            day:22,
            nameOfLanguage:'تایلندی',
            titleOfSource:'نظرات تیک تاک',
            titleOfAspect1:'وزن',
          },
          {
            id: 68,
            polarity:'مثبت',
            text:' بد بود',
            year: 1393,
            month:1,
            day:22,
            nameOfLanguage:'کره ای',
            titleOfSource:'گوگل',
            titleOfAspect1:' حافظه‌ی رم',
          },
          {
            id: 69,
            polarity:'خنثی',
            text:' جالب بود',
            year: 1393,
            month:1,
            day:22,
            nameOfLanguage:'هلندی',
            titleOfSource:'نظرات تیک تاک',
            titleOfAspect1:' نوع آهنربا',
          },        {
            id: 70,
            polarity:'منفی',
            text:' عالی بود',
            year: 1391,
            month:1,
            day:22,
            nameOfLanguage:'تایلندی',
            titleOfSource:'نظرات تیک تاک',
            titleOfAspect1:'وزن',
          },
          {
            id: 71,
            polarity:'خنثی',
            text:' جالب بود',
            year: 1398,
            month:1,
            day:22,
            nameOfLanguage:'هلندی',
            titleOfSource:'نظرات تیک تاک',
            titleOfAspect1:' نوع آهنربا',
          },];
